sonar.projectKey=FernandoMrq_teste_valid
sonar.organization=fernandomrq

sonar.sources=src,frontend/valid-os-web/src
sonar.tests=tests,frontend/valid-os-web/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*Tests/**/*.cs

sonar.exclusions=**/bin/**,**/obj/**,**/dist/**,**/node_modules/**,frontend/valid-os-web/public/**,**/Migrations/**

sonar.cs.opencover.reportsPaths=**/TestResults/**/coverage.opencover.xml
sonar.javascript.lcov.reportPaths=frontend/valid-os-web/coverage/lcov.info
sonar.typescript.lcov.reportPaths=frontend/valid-os-web/coverage/lcov.info

sonar.sourceEncoding=UTF-8
